name = "accounting-tool"
main = "src/index.js"
compatibility_date = "2024-11-01"

[assets]
directory = "../public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "accounting_tool"
database_id = "2ceab5de-1525-41ba-bd71-4a4305a22ee5"
